loadstring(game:HttpGet("https://raw.githubusercontent.com/nz-cat/Bot2/main/rrr03ejp39.lua"))()
loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/ThongBao/InputApi(NoEncode)"))()
loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/ThongBao/NotifyFullMoonOnly"))()
loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/ThongBao/AttackFix"))()
