loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/NewAc/attackgg.txt"))()

loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/NewAc/Api.luau.txt"))()

loadstring(game:HttpGet("https://github.com/TlDinhKhoi/Util/raw/refs/heads/main/NewAc/ApiTeddy.txt"))()

loadstring(game:HttpGet("https://api.luarmor.net/files/v4/loaders/0073e98329315d83a9786261b2f98d9c.lua"))()
